"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from mammoth_analytics.errors import MammothAnalyticsError
from mammoth_analytics.models import (
    addfeaturetoprofileop as models_addfeaturetoprofileop,
)
from mammoth_analytics.types import BaseModel, OptionalNullable, UNSET
from typing import Optional


class AddFeatureToProfileBadRequestErrorData(BaseModel):
    status_code: int

    detail: str

    extra: OptionalNullable[models_addfeaturetoprofileop.AddFeatureToProfileExtra] = (
        UNSET
    )


class AddFeatureToProfileBadRequestError(MammothAnalyticsError):
    r"""Validation Exception"""

    data: AddFeatureToProfileBadRequestErrorData

    def __init__(
        self,
        data: AddFeatureToProfileBadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
