"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from mammoth_analytics.errors import MammothAnalyticsError
from mammoth_analytics.models import (
    checkconnectoraccessop as models_checkconnectoraccessop,
)
from mammoth_analytics.types import BaseModel, OptionalNullable, UNSET
from typing import Optional


class CheckConnectorAccessBadRequestErrorData(BaseModel):
    status_code: int

    detail: str

    extra: OptionalNullable[models_checkconnectoraccessop.CheckConnectorAccessExtra] = (
        UNSET
    )


class CheckConnectorAccessBadRequestError(MammothAnalyticsError):
    r"""Validation Exception"""

    data: CheckConnectorAccessBadRequestErrorData

    def __init__(
        self,
        data: CheckConnectorAccessBadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
