"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from mammoth_analytics.errors import MammothAnalyticsError
from mammoth_analytics.models import createconnectorop as models_createconnectorop
from mammoth_analytics.types import BaseModel, OptionalNullable, UNSET
from typing import Optional


class CreateConnectorBadRequestErrorData(BaseModel):
    status_code: int

    detail: str

    extra: OptionalNullable[models_createconnectorop.CreateConnectorExtra] = UNSET


class CreateConnectorBadRequestError(MammothAnalyticsError):
    r"""Validation Exception"""

    data: CreateConnectorBadRequestErrorData

    def __init__(
        self,
        data: CreateConnectorBadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
