"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from mammoth_analytics.errors import MammothAnalyticsError
from mammoth_analytics.models import createfeatureop as models_createfeatureop
from mammoth_analytics.types import BaseModel, OptionalNullable, UNSET
from typing import Optional


class CreateFeatureBadRequestErrorData(BaseModel):
    status_code: int

    detail: str

    extra: OptionalNullable[models_createfeatureop.CreateFeatureExtra] = UNSET


class CreateFeatureBadRequestError(MammothAnalyticsError):
    r"""Validation Exception"""

    data: CreateFeatureBadRequestErrorData

    def __init__(
        self,
        data: CreateFeatureBadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
