"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from mammoth_analytics.errors import MammothAnalyticsError
from mammoth_analytics.models import getworkspaceusageop as models_getworkspaceusageop
from mammoth_analytics.types import BaseModel, OptionalNullable, UNSET
from typing import Optional


class GetWorkspaceUsageBadRequestErrorData(BaseModel):
    status_code: int

    detail: str

    extra: OptionalNullable[models_getworkspaceusageop.GetWorkspaceUsageExtra] = UNSET


class GetWorkspaceUsageBadRequestError(MammothAnalyticsError):
    r"""Validation Exception"""

    data: GetWorkspaceUsageBadRequestErrorData

    def __init__(
        self,
        data: GetWorkspaceUsageBadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
