"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from mammoth_analytics.errors import MammothAnalyticsError
from mammoth_analytics.models import transferownershipsop as models_transferownershipsop
from mammoth_analytics.types import BaseModel, OptionalNullable, UNSET
from typing import Optional


class TransferOwnershipsBadRequestErrorData(BaseModel):
    status_code: int

    detail: str

    extra: OptionalNullable[models_transferownershipsop.TransferOwnershipsExtra] = UNSET


class TransferOwnershipsBadRequestError(MammothAnalyticsError):
    r"""Validation Exception"""

    data: TransferOwnershipsBadRequestErrorData

    def __init__(
        self,
        data: TransferOwnershipsBadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
