"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .addconnectoraddonrequest import (
    AddConnectorAddonRequest,
    AddConnectorAddonRequestTypedDict,
)
from mammoth_analytics.types import BaseModel
from mammoth_analytics.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class AddConnectorAddonRequestRequestTypedDict(TypedDict):
    add_connector_addon_request: AddConnectorAddonRequestTypedDict
    workspace_id: int
    r"""Workspace refers to a collection of projects. Workspace ID is unique identifier for workspace."""


class AddConnectorAddonRequestRequest(BaseModel):
    add_connector_addon_request: Annotated[
        AddConnectorAddonRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    workspace_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ] = 2
    r"""Workspace refers to a collection of projects. Workspace ID is unique identifier for workspace."""
