"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mammoth_analytics.types import BaseModel
from mammoth_analytics.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class AddDataToWebhookUsingGetMethodRequestTypedDict(TypedDict):
    webhook_uri: str
    r"""API key of the webhook"""


class AddDataToWebhookUsingGetMethodRequest(BaseModel):
    webhook_uri: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ] = "4"
    r"""API key of the webhook"""
