"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .adduserspec import AddUserSpec, AddUserSpecTypedDict
from mammoth_analytics.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class AddUsersToProjectTypedDict(TypedDict):
    r"""Add user to a project. Only project_admin and project_analyst are allowed"""

    users: List[AddUserSpecTypedDict]
    r"""List of user IDs to add to project"""


class AddUsersToProject(BaseModel):
    r"""Add user to a project. Only project_admin and project_analyst are allowed"""

    users: List[AddUserSpec]
    r"""List of user IDs to add to project"""
