"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mammoth_analytics.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AddUserSeatsAddonRequestTypedDict(TypedDict):
    user_count: NotRequired[int]
    r"""Number of additional user seats to add"""


class AddUserSeatsAddonRequest(BaseModel):
    user_count: Optional[int] = 1
    r"""Number of additional user seats to add"""
