"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .automationpatchdata import AutomationPatchData, AutomationPatchDataTypedDict
from mammoth_analytics.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class AutomationPatchRequestTypedDict(TypedDict):
    r"""Update automation related details"""

    patch: List[AutomationPatchDataTypedDict]


class AutomationPatchRequest(BaseModel):
    r"""Update automation related details"""

    patch: List[AutomationPatchData]
