"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .automations_schema_conditionschema import (
    AutomationsSchemaConditionSchema,
    AutomationsSchemaConditionSchemaTypedDict,
)
from enum import Enum
from mammoth_analytics.types import BaseModel
from typing_extensions import TypedDict


class AutomationConditionSchemaConditionType(str, Enum):
    r"""Condition Type"""

    AT_SPECIFIC_TIME = "at_specific_time"
    NEW_DATA_ADDITION_IN_FOLDER = "new_data_addition_in_folder"


class AutomationConditionSchemaTypedDict(TypedDict):
    condition_type: AutomationConditionSchemaConditionType
    r"""Condition Type"""
    details: AutomationsSchemaConditionSchemaTypedDict
    r"""Condition Details"""


class AutomationConditionSchema(BaseModel):
    condition_type: AutomationConditionSchemaConditionType
    r"""Condition Type"""

    details: AutomationsSchemaConditionSchema
    r"""Condition Details"""
