"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from mammoth_analytics.types import BaseModel
from typing_extensions import TypedDict


class ChangeColumnTypeCType(str, Enum):
    r"""Column Data Type"""

    TEXT = "text"
    NUMERIC = "numeric"
    DATE = "date"


class ChangeColumnTypeTypedDict(TypedDict):
    c_id: str
    r"""Column id"""
    c_type: ChangeColumnTypeCType
    r"""Column Data Type"""


class ChangeColumnType(BaseModel):
    c_id: str
    r"""Column id"""

    c_type: ChangeColumnTypeCType
    r"""Column Data Type"""
