"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clientappfieldsschema import ClientAppFieldsSchema, ClientAppFieldsSchemaTypedDict
from .clientappfullschema import ClientAppFullSchema, ClientAppFullSchemaTypedDict
from .clientappminschema import ClientAppMinSchema, ClientAppMinSchemaTypedDict
from .clientappschema import ClientAppSchema, ClientAppSchemaTypedDict
from .clientappstdschema import ClientAppStdSchema, ClientAppStdSchemaTypedDict
from mammoth_analytics.types import BaseModel
from typing import List, Union
from typing_extensions import TypeAliasType, TypedDict


ResultTypedDict = TypeAliasType(
    "ResultTypedDict",
    Union[
        ClientAppMinSchemaTypedDict,
        ClientAppSchemaTypedDict,
        ClientAppFieldsSchemaTypedDict,
        ClientAppStdSchemaTypedDict,
        ClientAppFullSchemaTypedDict,
    ],
)


Result = TypeAliasType(
    "Result",
    Union[
        ClientAppMinSchema,
        ClientAppSchema,
        ClientAppFieldsSchema,
        ClientAppStdSchema,
        ClientAppFullSchema,
    ],
)


class ClientAppsListTypedDict(TypedDict):
    result: List[ResultTypedDict]


class ClientAppsList(BaseModel):
    result: List[Result]
