"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apiv2_conditional_formatting_schema_columnschema import (
    Apiv2ConditionalFormattingSchemaColumnSchema,
    Apiv2ConditionalFormattingSchemaColumnSchemaTypedDict,
)
from enum import Enum
from mammoth_analytics.types import BaseModel
from typing import Dict
from typing_extensions import TypedDict


class ConditionPatchDataOperation(str, Enum):
    r"""Operation"""

    REPLACE = "replace"


class ConditionPatchDataPath(str, Enum):
    r"""Path"""

    CONDITION = "condition"


class ConditionPatchDataTypedDict(TypedDict):
    op: ConditionPatchDataOperation
    r"""Operation"""
    path: ConditionPatchDataPath
    r"""Path"""
    value: Dict[str, Apiv2ConditionalFormattingSchemaColumnSchemaTypedDict]
    r"""Value to update automation details"""


class ConditionPatchData(BaseModel):
    op: ConditionPatchDataOperation
    r"""Operation"""

    path: ConditionPatchDataPath
    r"""Path"""

    value: Dict[str, Apiv2ConditionalFormattingSchemaColumnSchema]
    r"""Value to update automation details"""
