"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .datasetcreationspec import DatasetCreationSpec, DatasetCreationSpecTypedDict
from mammoth_analytics.types import BaseModel
from mammoth_analytics.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Any, Dict, List, Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class CreateDatasetsRequestTypedDict(TypedDict):
    dataset_creation_spec: DatasetCreationSpecTypedDict
    workspace_id: int
    r"""Workspace refers to a collection of projects. Workspace ID is unique identifier for workspace."""
    project_id: int
    r"""Project ID of the workspace"""


class CreateDatasetsRequest(BaseModel):
    dataset_creation_spec: Annotated[
        DatasetCreationSpec,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    workspace_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ] = 2
    r"""Workspace refers to a collection of projects. Workspace ID is unique identifier for workspace."""

    project_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ] = 1
    r"""Project ID of the workspace"""


CreateDatasetsExtraTypedDict = TypeAliasType(
    "CreateDatasetsExtraTypedDict", Union[Dict[str, Any], List[Any]]
)


CreateDatasetsExtra = TypeAliasType(
    "CreateDatasetsExtra", Union[Dict[str, Any], List[Any]]
)
