"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from mammoth_analytics.types import BaseModel
from typing import Union
from typing_extensions import TypeAliasType, TypedDict


class RefreshSourceType(str, Enum):
    r"""Source Type"""

    WEBHOOK = "webhook"
    FILE = "file"
    CLOUD = "cloud"


SourceIDTypedDict = TypeAliasType("SourceIDTypedDict", Union[int, str])
r"""Source ID"""


SourceID = TypeAliasType("SourceID", Union[int, str])
r"""Source ID"""


class DataRefreshTypedDict(TypedDict):
    refresh_source_type: RefreshSourceType
    r"""Source Type"""
    source_id: SourceIDTypedDict
    r"""Source ID"""


class DataRefresh(BaseModel):
    refresh_source_type: RefreshSourceType
    r"""Source Type"""

    source_id: SourceID
    r"""Source ID"""
