"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Any, Dict, List, Union
from typing_extensions import TypeAliasType


DeleteAvatarUnauthorizedExtraTypedDict = TypeAliasType(
    "DeleteAvatarUnauthorizedExtraTypedDict", Union[Dict[str, Any], List[Any]]
)


DeleteAvatarUnauthorizedExtra = TypeAliasType(
    "DeleteAvatarUnauthorizedExtra", Union[Dict[str, Any], List[Any]]
)


DeleteAvatarBadRequestExtraTypedDict = TypeAliasType(
    "DeleteAvatarBadRequestExtraTypedDict", Union[Dict[str, Any], List[Any]]
)


DeleteAvatarBadRequestExtra = TypeAliasType(
    "DeleteAvatarBadRequestExtra", Union[Dict[str, Any], List[Any]]
)
