"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mammoth_analytics.types import BaseModel
from mammoth_analytics.utils import FieldMetadata, PathParamMetadata
from typing import Any, Dict, List, Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class DeletePlanRequestTypedDict(TypedDict):
    plan_id: int


class DeletePlanRequest(BaseModel):
    plan_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


DeletePlanExtraTypedDict = TypeAliasType(
    "DeletePlanExtraTypedDict", Union[Dict[str, Any], List[Any]]
)


DeletePlanExtra = TypeAliasType("DeletePlanExtra", Union[Dict[str, Any], List[Any]])
