"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mammoth_analytics.types import BaseModel
from mammoth_analytics.utils import FieldMetadata, PathParamMetadata
from typing import Any, Dict, List, Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class DeleteFeatureProfileRequestTypedDict(TypedDict):
    profile_id: int


class DeleteFeatureProfileRequest(BaseModel):
    profile_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


DeleteFeatureProfileExtraTypedDict = TypeAliasType(
    "DeleteFeatureProfileExtraTypedDict", Union[Dict[str, Any], List[Any]]
)


DeleteFeatureProfileExtra = TypeAliasType(
    "DeleteFeatureProfileExtra", Union[Dict[str, Any], List[Any]]
)
