"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dsconfigpatchdata import DsConfigPatchData, DsConfigPatchDataTypedDict
from mammoth_analytics.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class DsConfigPatchRequestTypedDict(TypedDict):
    r"""Update query for the dataset"""

    patch: List[DsConfigPatchDataTypedDict]


class DsConfigPatchRequest(BaseModel):
    r"""Update query for the dataset"""

    patch: List[DsConfigPatchData]
