"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mammoth_analytics.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ExtractSheetsPatchTypedDict(TypedDict):
    sheets: List[str]
    r"""Sheets to extract"""
    delete_file_after_extract: NotRequired[bool]
    r"""Whether to delete main file after sheet extraction or not"""
    combine_after_extract: NotRequired[bool]
    r"""Whether to combine sheets after sheet extraction or not"""


class ExtractSheetsPatch(BaseModel):
    sheets: List[str]
    r"""Sheets to extract"""

    delete_file_after_extract: Optional[bool] = True
    r"""Whether to delete main file after sheet extraction or not"""

    combine_after_extract: Optional[bool] = False
    r"""Whether to combine sheets after sheet extraction or not"""
