"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .featureprofileschema import FeatureProfileSchema, FeatureProfileSchemaTypedDict
from mammoth_analytics.types import BaseModel
from typing_extensions import TypedDict


class FeatureProfileResponseSchemaTypedDict(TypedDict):
    feature_profile: FeatureProfileSchemaTypedDict
    message: str


class FeatureProfileResponseSchema(BaseModel):
    feature_profile: FeatureProfileSchema

    message: str
