"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .filesource import FileSource, FileSourceTypedDict
from enum import Enum
from mammoth_analytics.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class FileInfoType(str, Enum):
    r"""Type of the source"""

    FILE = "file"
    SKETCH = "sketch"
    CLOUD = "cloud"
    ABSTRACT = "abstract"
    APPEND = "append"


class FileInfoTypedDict(TypedDict):
    details: FileSourceTypedDict
    r"""Details of the file ds source"""
    type: NotRequired[FileInfoType]
    r"""Type of the source"""


class FileInfo(BaseModel):
    details: FileSource
    r"""Details of the file ds source"""

    type: Optional[FileInfoType] = FileInfoType.SKETCH
    r"""Type of the source"""
