"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mammoth_analytics.types import BaseModel
from typing_extensions import TypedDict


class ConnectionConfigTypedDict(TypedDict):
    r"""Connection Config"""


class ConnectionConfig(BaseModel):
    r"""Connection Config"""


class GetConnectionSchemaTypedDict(TypedDict):
    connection_key: str
    r"""Connection Key"""
    connection_config: ConnectionConfigTypedDict
    r"""Connection Config"""


class GetConnectionSchema(BaseModel):
    connection_key: str
    r"""Connection Key"""

    connection_config: ConnectionConfig
    r"""Connection Config"""
