"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mammoth_analytics.types import BaseModel
from mammoth_analytics.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetJobRequestTypedDict(TypedDict):
    job_id: int
    r"""Job id is unique identifier for Job object. If processing is not completed, it will return processing otherwise it will have information about Job"""


class GetJobRequest(BaseModel):
    job_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ] = 10
    r"""Job id is unique identifier for Job object. If processing is not completed, it will return processing otherwise it will have information about Job"""
