"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mammoth_analytics.types import BaseModel
from typing_extensions import TypedDict


class GetPlanSchemaTypedDict(TypedDict):
    plan: str
    r"""The plan of the workspace"""


class GetPlanSchema(BaseModel):
    plan: str
    r"""The plan of the workspace"""
