"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mammoth_analytics.types import BaseModel
from typing_extensions import TypedDict


class InstanceSchemaTypedDict(TypedDict):
    tag: str
    r"""Tag of the instance"""
    id: str
    r"""ID of the instance"""


class InstanceSchema(BaseModel):
    tag: str
    r"""Tag of the instance"""

    id: str
    r"""ID of the instance"""
