"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from enum import Enum
from mammoth_analytics.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict


class ItemTaskInfoStatus(str, Enum):
    DELETED = "deleted"
    EXECUTED = "executed"
    EXECUTING = "executing"
    EDITED = "edited"
    ADDED = "added"
    SUSPENDED = "suspended"
    SUSPENDING = "suspending"


class ItemTaskInfoParamsTypedDict(TypedDict):
    pass


class ItemTaskInfoParams(BaseModel):
    pass


class TransformStatus(str, Enum):
    INIT = "INIT"
    PROCESSING = "PROCESSING"
    LOCKED = "LOCKED"
    DONE = "DONE"
    ERROR = "ERROR"
    INACTIVE = "INACTIVE"
    REFERROR = "REFERROR"
    QUEUED = "QUEUED"
    IGNORED = "IGNORED"
    EXCEPTION = "EXCEPTION"
    SUSPENDED = "SUSPENDED"


class PrevMetadataTypedDict(TypedDict):
    pass


class PrevMetadata(BaseModel):
    pass


class ItemTaskInfoReferenceErrorsTypedDict(TypedDict):
    pass


class ItemTaskInfoReferenceErrors(BaseModel):
    pass


class ItemTaskInfoTypedDict(TypedDict):
    id: NotRequired[Nullable[int]]
    dataview_id: NotRequired[Nullable[int]]
    sequence: NotRequired[Nullable[int]]
    status: NotRequired[Nullable[ItemTaskInfoStatus]]
    created_at: NotRequired[Nullable[datetime]]
    params: NotRequired[Nullable[ItemTaskInfoParamsTypedDict]]
    transform_status: NotRequired[Nullable[TransformStatus]]
    prev_metadata: NotRequired[Nullable[List[PrevMetadataTypedDict]]]
    reordered: NotRequired[Nullable[bool]]
    reference_errors: NotRequired[Nullable[ItemTaskInfoReferenceErrorsTypedDict]]
    data_pass_through: NotRequired[Nullable[bool]]
    data_size: NotRequired[Nullable[int]]
    row_count: NotRequired[Nullable[int]]
    execution_start_time: NotRequired[Nullable[datetime]]
    execution_end_time: NotRequired[Nullable[datetime]]


class ItemTaskInfo(BaseModel):
    id: OptionalNullable[int] = UNSET

    dataview_id: OptionalNullable[int] = UNSET

    sequence: OptionalNullable[int] = UNSET

    status: OptionalNullable[ItemTaskInfoStatus] = UNSET

    created_at: OptionalNullable[datetime] = UNSET

    params: OptionalNullable[ItemTaskInfoParams] = UNSET

    transform_status: OptionalNullable[TransformStatus] = UNSET

    prev_metadata: OptionalNullable[List[PrevMetadata]] = UNSET

    reordered: OptionalNullable[bool] = UNSET

    reference_errors: OptionalNullable[ItemTaskInfoReferenceErrors] = UNSET

    data_pass_through: OptionalNullable[bool] = UNSET

    data_size: OptionalNullable[int] = UNSET

    row_count: OptionalNullable[int] = UNSET

    execution_start_time: OptionalNullable[datetime] = UNSET

    execution_end_time: OptionalNullable[datetime] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "id",
            "dataview_id",
            "sequence",
            "status",
            "created_at",
            "params",
            "transform_status",
            "prev_metadata",
            "reordered",
            "reference_errors",
            "data_pass_through",
            "data_size",
            "row_count",
            "execution_start_time",
            "execution_end_time",
        ]
        nullable_fields = [
            "id",
            "dataview_id",
            "sequence",
            "status",
            "created_at",
            "params",
            "transform_status",
            "prev_metadata",
            "reordered",
            "reference_errors",
            "data_pass_through",
            "data_size",
            "row_count",
            "execution_start_time",
            "execution_end_time",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
