"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .addexportspec import AddExportSpec, AddExportSpecTypedDict
from enum import Enum
from mammoth_analytics.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class ItemExportPatchOp(str, Enum):
    r"""Operation e.g. replace, command etc"""

    REPLACE = "replace"
    COMMAND = "command"


class ItemExportPatchPath(str, Enum):
    r"""Path to part of the resource being modified"""

    RUN = "run"
    SUSPEND = "suspend"
    RESTORE = "restore"
    DISCARD = "discard"
    PARAMS = "params"


class ItemExportPatchTypedDict(TypedDict):
    op: ItemExportPatchOp
    r"""Operation e.g. replace, command etc"""
    path: ItemExportPatchPath
    r"""Path to part of the resource being modified"""
    value: NotRequired[Nullable[AddExportSpecTypedDict]]
    r"""Patch value, the path of the resource to modified with"""


class ItemExportPatch(BaseModel):
    op: ItemExportPatchOp
    r"""Operation e.g. replace, command etc"""

    path: ItemExportPatchPath
    r"""Path to part of the resource being modified"""

    value: OptionalNullable[AddExportSpec] = UNSET
    r"""Patch value, the path of the resource to modified with"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["value"]
        nullable_fields = ["value"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
