"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mammoth_analytics.types import BaseModel
from typing_extensions import TypedDict


class PatchValueReorderExportItemTypedDict(TypedDict):
    export_id: int
    reordered: bool
    end_of_pipeline: bool


class PatchValueReorderExportItem(BaseModel):
    export_id: int

    reordered: bool

    end_of_pipeline: bool
