"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .planschema import PlanSchema, PlanSchemaTypedDict
from mammoth_analytics.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PlanListResponseSchemaTypedDict(TypedDict):
    plans: List[PlanSchemaTypedDict]


class PlanListResponseSchema(BaseModel):
    plans: List[PlanSchema]
