"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .projectuserpatchop import ProjectUserPatchOp, ProjectUserPatchOpTypedDict
from mammoth_analytics.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ProjectUserPatchTypedDict(TypedDict):
    r"""Add user to a project"""

    patch: List[ProjectUserPatchOpTypedDict]


class ProjectUserPatch(BaseModel):
    r"""Add user to a project"""

    patch: List[ProjectUserPatchOp]
