"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .projectpatchop import ProjectPatchOp, ProjectPatchOpTypedDict
from mammoth_analytics.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ProjectPatchTypedDict(TypedDict):
    r"""Rename project to 'My Project'"""

    patches: List[ProjectPatchOpTypedDict]


class ProjectPatch(BaseModel):
    r"""Rename project to 'My Project'"""

    patches: List[ProjectPatchOp]
