"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .projectschema import ProjectSchema, ProjectSchemaTypedDict
from mammoth_analytics.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ProjectListTypedDict(TypedDict):
    projects: List[ProjectSchemaTypedDict]
    next: str
    r"""URI for next page of data"""
    offset: NotRequired[int]
    limit: NotRequired[int]


class ProjectList(BaseModel):
    projects: List[ProjectSchema]

    next: str
    r"""URI for next page of data"""

    offset: Optional[int] = 0

    limit: Optional[int] = 50
