"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mammoth_analytics.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ProjectPropertiesTypedDict(TypedDict):
    r"""Properties of project"""

    color: NotRequired[str]
    r"""Color of project"""


class ProjectProperties(BaseModel):
    r"""Properties of project"""

    color: Optional[str] = "#EB661E"
    r"""Color of project"""
