"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mammoth_analytics.types import BaseModel
from mammoth_analytics.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from typing import Any, Dict, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class RemoveUserFromWorkspaceRequestTypedDict(TypedDict):
    workspace_id: int
    r"""Workspace refers to a collection of projects. Workspace ID is unique identifier for workspace."""
    ids: NotRequired[str]
    r"""Comma separated user ids"""
    invite_ids: NotRequired[str]
    r"""Comma separated invitation ids"""


class RemoveUserFromWorkspaceRequest(BaseModel):
    workspace_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ] = 2
    r"""Workspace refers to a collection of projects. Workspace ID is unique identifier for workspace."""

    ids: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = ""
    r"""Comma separated user ids"""

    invite_ids: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = ""
    r"""Comma separated invitation ids"""


RemoveUserFromWorkspaceExtraTypedDict = TypeAliasType(
    "RemoveUserFromWorkspaceExtraTypedDict", Union[Dict[str, Any], List[Any]]
)


RemoveUserFromWorkspaceExtra = TypeAliasType(
    "RemoveUserFromWorkspaceExtra", Union[Dict[str, Any], List[Any]]
)
