"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .rruleschema import RruleSchema, RruleSchemaTypedDict
from .workitemschema import WorkItemSchema, WorkItemSchemaTypedDict
from mammoth_analytics.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict


class SchedulePostRequestSchemaTypedDict(TypedDict):
    r"""Details of a schedule to be created"""

    rrule: RruleSchemaTypedDict
    work_items: NotRequired[Nullable[List[WorkItemSchemaTypedDict]]]


class SchedulePostRequestSchema(BaseModel):
    r"""Details of a schedule to be created"""

    rrule: RruleSchema

    work_items: OptionalNullable[List[WorkItemSchema]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["work_items"]
        nullable_fields = ["work_items"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
