"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updatestoragetiersrequestschema import (
    UpdateStorageTiersRequestSchema,
    UpdateStorageTiersRequestSchemaTypedDict,
)
from mammoth_analytics.types import BaseModel
from mammoth_analytics.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Any, Dict, List, Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class UpdateStorageTiersRequestTypedDict(TypedDict):
    plan_id: int
    update_storage_tiers_request_schema: UpdateStorageTiersRequestSchemaTypedDict


class UpdateStorageTiersRequest(BaseModel):
    plan_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    update_storage_tiers_request_schema: Annotated[
        UpdateStorageTiersRequestSchema,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


UpdateStorageTiersExtraTypedDict = TypeAliasType(
    "UpdateStorageTiersExtraTypedDict", Union[Dict[str, Any], List[Any]]
)


UpdateStorageTiersExtra = TypeAliasType(
    "UpdateStorageTiersExtra", Union[Dict[str, Any], List[Any]]
)
