"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .adminworkspaceuserpatchop import (
    AdminWorkspaceUserPatchOp,
    AdminWorkspaceUserPatchOpTypedDict,
)
from mammoth_analytics.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class WorkspaceUserPatchTypedDict(TypedDict):
    r"""Update/change user roles in the workspace"""

    patch: List[AdminWorkspaceUserPatchOpTypedDict]


class WorkspaceUserPatch(BaseModel):
    r"""Update/change user roles in the workspace"""

    patch: List[AdminWorkspaceUserPatchOp]
