"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from mammoth_analytics.types import BaseModel
from typing_extensions import TypedDict


class WorkspaceMinSchemaTypedDict(TypedDict):
    id: int
    r"""ID of the workspace"""
    name: str
    r"""Name of the workspace to be created"""
    status: str
    r"""Status of the workspace"""
    last_updated_at: datetime
    r"""Last Updated At of the workspace"""


class WorkspaceMinSchema(BaseModel):
    id: int
    r"""ID of the workspace"""

    name: str
    r"""Name of the workspace to be created"""

    status: str
    r"""Status of the workspace"""

    last_updated_at: datetime
    r"""Last Updated At of the workspace"""
